import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewparent.java
 *
 * Created on Nov 10, 2017, 4:15:53 PM
 */

/**
 *
 * @author Anu
 */
public class viewparent extends javax.swing.JFrame {

    /** Creates new form viewparent */
    public viewparent() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        d1.setIconImage(null);
        d1.setMinimumSize(new java.awt.Dimension(700, 400));
        d1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Attendance Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        d1.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 50));

        l1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        l1.setText("1");
        d1.getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 20));

        l2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l2.setText("3");
        d1.getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 30, 20));

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setText("3");
        d1.getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 30, 20));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Scholar No.");
        d1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, 20));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Class");
        d1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 60, 20));

        jButton4.setText("Fee Record");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        d1.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 130, 50));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Present", "Absent"
            }
        ));
        tb1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tb1);

        d1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 120));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Installment No.", "Installment Date", "Installment Amount", "Paid"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        d1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 440, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed (14).gif"))); // NOI18N
        d1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 370, 130));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Aparajita", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setOpaque(true);
        d1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 820, 430));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel2.setText("I.D.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 60, 20));

        jButton2.setFont(new java.awt.Font("Californian FB", 3, 24)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 90, 40));

        jButton7.setFont(new java.awt.Font("Californian FB", 3, 24)); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 210, 100, 40));

        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 60, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (20).jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a= t1.getText();
        String b= new String(t2.getPassword());
       String v = "";
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","Nidhi98299");
            Statement st =con.createStatement();
            String q= " select password from parent where login_id ='"+a+"' ;";
            String z= "select login_id from parent where login_id ='"+a+"'  ; " ;
            ResultSet qw = st.executeQuery(z);
            if (qw.next()) {
                String d =qw.getString("login_id");
                if (d.compareTo("")==0)

                    JOptionPane.showMessageDialog(null,"check password");

            } else JOptionPane.showMessageDialog(null,"invalid id");


            ResultSet rs = st.executeQuery(q);
            if (rs.next()) {
                String c =rs.getString("password");
                if (c.compareTo(b)==0) {
                    d1.setVisible(true);

                } else
                    JOptionPane.showMessageDialog(null,"check password");

            }


        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());

        }
    try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","Nidhi98299");
Statement st =con.createStatement();
String s= "select scholar_no from parent where login_id= '"+a+"';";
ResultSet rs = st.executeQuery(s);
if(rs.next())

     v = rs.getString("scholar_no");

}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}


int k=Integer.parseInt(v);
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","Nidhi98299");
Statement st =con.createStatement();
String z= "select * from student where scholar_no= "+k+";";
ResultSet rs = st.executeQuery(z);
if(rs.next())
{String i= rs.getString("name");
 String j= rs.getString("scholar_no");
 String l= rs.getString("class");
l1.setText(""+i);
l2.setText(""+j);
l3.setText(""+l);
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}

t1.setText("");
t2.setText("");






        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int a=Integer.parseInt(l3.getText());
 int b=Integer.parseInt(l2.getText());
 DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","Nidhi98299");
Statement st =con.createStatement();
String q= " select present,absent from class_"+a+" where scholar_no= "+b+" ; ";
ResultSet rs = st.executeQuery(q);
int i=0;
while(rs.next())
{
 String d=rs.getString("present");
 String e=rs.getString("absent");


  model.addRow(new Object[] {d,e} );
i=i+1;
}
if(i==0)
JOptionPane.showMessageDialog(null,"No Record Found!");
}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int a=Integer.parseInt(l3.getText());
 int b=Integer.parseInt(l2.getText());
 DefaultTableModel model=(DefaultTableModel)tb2.getModel();
try
{
Class.forName("java.sql.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost/test","root","Nidhi98299");
Statement st = con.createStatement();
String q= " select installment_no, installment_date, installment_amount, paid from fees where scholar_no = "+b+" ;";
ResultSet rs = st.executeQuery(q);
int i=0;
while(rs.next())
{
 String d=rs.getString("installment_no");
 String e=rs.getString("installment_date");
String j=rs.getString("installment_amount");
String k=rs.getString("paid");
  model.addRow(new Object[] {d,e,j,k} );
i=i+1;
}
if(i==0)
JOptionPane.showMessageDialog(null,"No Record Found!");
}


catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        t1.setText("");t2.setText("");      // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new home().setVisible(true);         // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewparent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog d1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    // End of variables declaration//GEN-END:variables

}
